########################################################  figure 1c  ###############################################################################

library(ggplot2)

genetype_degree <- read.table("repeat25sample_mergemod_intramoduleconne-gs-mm_gene-id-type-chr-name-degree.txt",header=F)

table(genetype_degree[,3])

table(genetype_degree[,4])

table(genetype_degree[,7])

names(genetype_degree) <- c("geneid","id","type1","chr","symble","intra_degree","type2","type3")


mytheme<-theme_bw(base_size=9)+
         theme(
	 	plot.margin = unit(c(0.1,0.1,0.1,0.1),"cm"),
		panel.grid.major = element_blank(),
		panel.grid.minor = element_blank(),
		panel.border = element_rect(color="white",fill=NA),
		legend.title = element_blank(),
		legend.text = element_text(size=rel(1)),
		axis.title.y = element_text(colour="black",size=rel(1),vjust = 1),
		axis.title.x = element_text(colour="black",size=rel(1),vjust = 0),
		axis.text.x = element_text(colour="black",size=9),
		axis.text.y = element_text(colour="black",size=9),
		axis.ticks.x = element_line(color="black",size=0.5291),
		axis.ticks.y = element_line(color="black",size=0.5291),
		axis.line = element_line(color="black",size=0.5291)
		)

colors<- c("blue","red")
ggplot(genetype_degree,aes(intra_degree,fill=type2)) + scale_fill_manual(values=colors)+ geom_density(alpha = 0.5, size=0.3527) + mytheme + theme(legend.position=c(0.75,0.85),legend.key.size=unit(0.3,"cm"),legend.text=element_text(margin=margin(0.5,0,0.5,0,"mm")))

# base_size=10.5, unit is point.
# size=0.3527 unit is mm, means 1 point. size =0.5291, means 1.5 points.
# if you have many colors, so the vector colors can be generated by for exampe, colors <- rainbow(n,...); n is number of colors, type ?Palettes for more details.

ggsave("figure1c_Genes.tiff", width=2.4, height=1.6, type="cairo", dpi=600)

# plot can be saved in a variable, and then use print() to generate the plot
# eg.: 	p <- ggplot();
#	png("mtcars.png")
#	print(p)
#	dev.off()


########################################################  figure 1e  ###############################################################################

###  strategy 1:

genetype_top25degree <- genetype_degree[which(genetype_degree$intra_degree>0.75),]

colors<- c("blue","red")

ggplot(genetype_top25degree,aes(group=type2,fill=type2)) + 
	scale_fill_manual(values=colors) +
	geom_area(aes(x=chr,y=..prop..),stat="count",position="identity",color="black",alpha = 0.5, size=0.3527) +
	scale_x_discrete(limits = c("chr1","chr2","chr3","chr4","chr5","chr6","chr7","chr8","chr9","chr10","chr11","chr12","chr13","chr14","chr15","chr16","chr17","chr18","chr19","chrX","chrY")) +
	mytheme + theme(legend.position=c(0.75,0.85),legend.key.size=unit(0.3,"cm"),legend.text=element_text(margin=margin(0.5,0,0.5,0,"mm")),axis.title.x=element_blank(),axis.title.y=element_blank(),axis.text.x = element_text(angle=45,hjust=1)) +
	scale_y_continuous(labels = scales::percent)

ggsave("figure1e_Genes.tiff", width=3.6, height=2.4, type="cairo", dpi=600)


###  strategy 2: (in use)

genetype_top25degree <- read.table("genetype_top25degree.txt",sep = "\t",header=T)

ggplot(genetype_top25degree,aes(x=chr,y=proportion,group=type,fill=type)) +
	scale_fill_manual(values=colors) +
	geom_area(stat="identity",position="identity",color="black",alpha = 0.5, size=0.3527) +
	scale_x_discrete(limits = c("chr1","chr2","chr3","chr4","chr5","chr6","chr7","chr8","chr9","chr10","chr11","chr12","chr13","chr14","chr15","chr16","chr17","chr18","chr19","chrX","chrY")) +
	mytheme + theme(legend.position=c(0.75,0.85),legend.key.size=unit(0.3,"cm"),legend.text=element_text(margin=margin(0.5,0,0.5,0,"mm")),axis.title.x=element_blank(),axis.title.y=element_blank(),axis.text.x = element_text(angle=45,hjust=1)) +
	scale_y_continuous(labels = scales::percent)


ggsave("figure1e_Genes.tiff", width=4.5, height=2, type="cairo", dpi=600)

########################################################  figure 1f  ###############################################################################

biotype.abund_3catalog <- read.table("biotype-abundance_3catalogs.txt",sep = "\t",header=T)
colors <- rainbow(7)
ggplot(biotype.abund_3catalog,aes(x=catalog,y=number,group=biotype,fill=biotype)) +
	geom_area(position="fill",stat="identity",color="black",alpha = 0.5, size=0.3527) +
	scale_fill_manual(values=colors) +
	scale_x_discrete(limits = c("annotated"," expressed","essential")) +
	mytheme + theme(legend.key.size=unit(0.5,"cm"),axis.title.x=element_blank(),axis.title.y=element_blank(),axis.text.x = element_text(angle=45,hjust=1)) +

methods 2: (use)

ggplot(biotype.abund_3catalog,aes(x=id,y=number,group=biotype,fill=biotype)) +
        geom_area(position="fill",stat="identity",color="black",alpha=0.75, size=0.3527) +
	scale_fill_manual(values=colors) +
	scale_x_continuous(breaks = 1:3,labels = c("annotated"," expressed","essential")) +
	scale_y_continuous(labels = scales::percent) +
	mytheme + theme(legend.key.size=unit(0.5,"cm"),axis.title.x=element_blank(),axis.title.y=element_blank(),axis.text.x = element_text(angle=45,hjust=1))

ggsave("biotype.abund_3catalog.tiff", width=4.5, height=2, type="cairo", dpi=300)


########################################################  figure 1b  ###############################################################################

library(WGCNA)
load("repeat25sample_sftpower_dynamicLables_dynamicColors_geneTree.RData")
load("repeat25sample_MEs_ModuleLables_ModuleColors_geneTree.RData")
mergedColors = moduleColors

tiff(file="figure1b_Genes.tiff",width=3.6, height=2.4, units="in",type="cairo",pointsize=9,res=600)

plotDendroAndColors(geneTree, cbind(dynamicColors, mergedColors),c("dynamic tree cut","merged modules"),main="",dendroLabels = FALSE, hang = 0.025,addGuide = TRUE, guideHang = 0.05,ylab="height", family="sans", guideCount=30,marAll=c(0.1,6.5,0.2,0),tcl=-0.25,cex.colorLabels=1)

dev.off()


########################################################  figure 2a  ###############################################################################

heatmap83lnc <- read.table("83lncRNA.txt",header=T,row.names=1)
# matrix83lnc <- as.matrix(heatmap83lnc[,2:3])
# rownames(matrix83lnc) <- heatmap83lnc[,1]
# colnames(matrix83lnc) <- c("malignant","normal")
pheatmap(log(heatmap83lnc+1),color = colorRampPalette(c("blue","white","red"))(200),scale = "column",cluster_rows=F,show_rownames=F,border_color = NA,legend_breaks = NA,legend_labels=NA)

# strategy 1 (pheatmap):

pheatmap(log(heatmap83lnc+1),color = colorRampPalette(c("blue","white","red"))(200),scale = "none",cluster_rows=F,show_rownames=F,border_color = NA,
	legend_breaks = c(1,3,5),treeheight_col=10,breaks=c(seq(0,0.5,0.005),seq(0.545,5,0.045)),gaps_row = 21,angle_col=0,fontsize=9,
	annotation_row=annotation_row,annotation_names_row=F,font.label=1
	)
	annotation_row=data.frame(enriched=factor(rep(c("enriched in normal","enriched in malignant"),c(21,62)))),
	rownames(annotation_row)=rownames(heatmap83lnc)


tiff(file="figure2a.tiff",width=2, height=2, units="in",type="cairo",pointsize=9,res=300)

# strategy 2 (ComplexHeatmap, use):

library(ComplexHeatmap)
heatmap194lnc <- read.table("194lncRNA.txt",header=T,row.names=1)
ht <- Heatmap(log(heatmap194lnc[,1:2]+1),col=circlize::colorRamp2(breaks=c(0,0.75,3),c("blue","white","red")),
	column_dend_height = unit(0.3, "cm"),column_labels=c("diff. arrest","normal diff."),column_names_rot = 45,column_names_centered=F, column_names_gp=gpar(fontsize=9),
	cluster_rows = FALSE, show_row_names = FALSE,
	row_split=factor(rep(c("72\nlncRNAs", "122\nlncRNAs"), c(72,122)),levels=c("72\nlncRNAs","122\nlncRNAs")),row_title_gp = gpar(font=1,fontsize=9),
	border = TRUE, show_heatmap_legend=F, 
	# width=unit(0.5,"npc"), height=unit(2,"in"),
	heatmap_width = unit(1.5, "in"), heatmap_height = unit(1.95, "in"),
	right_annotation =rowAnnotation(qvalue=anno_points(heatmap194lnc$qvalue,
					pch=16, size=unit(rep(1,194),"points"),width=unit(0.75,"cm"),
					axis_param = list(
							side = "top",gp=gpar(fontsize=9),
							at = c(0, 0.05),
							labels_rot=0
							)),
					show_annotation_name=T,annotation_name_gp=gpar(fontsize=9),annotation_name_rot=0),
	# heatmap_legend_param=list(title = "log(FPKM)",title_position="topleft",title_gp = gpar(font=1,fontsize=9),at=c(0,2.5,5),labels_gp = gpar(fontsize=9, font = 1))
	)

lgd = Legend(col_fun=circlize::colorRamp2(breaks=c(0,0.75,3),c("blue","white","red")),title = "log(FPKM)",title_position="topleft",title_gp = gpar(font=1,fontsize=9),at=c(0,4,8),labels_gp = gpar(fontsize=9, font = 1),title_gap=unit(2,"mm"))


tiff(file="figure2a_Genes.tiff",width=2.1, height=2, units="in",type="cairo",pointsize=9,res=600)
draw(ht,padding=unit(c(0,0.075,0.05,0.8),"in"))
draw(lgd, x = unit(0.85, "npc"), y = unit(0.7, "npc"))
dev.off()

########################################################  figure 4a  ###############################################################################

heatmapGdal1 <- read.table("de830genes_fpkm_sortFC.txt",header=T,row.names=1)

#  strategy 1:
pheatmap(log(heatmapGdal1[,1:4]+1),color = colorRampPalette(c("blue","white","red"))(200),scale = "row",cluster_rows=F,cluster_columns=F, show_rownames=F,border_color = NA,legend_breaks = NA,legend_labels=NA)

# strategy 2: (use)
library(ComplexHeatmap)
ht <- Heatmap(t(scale(t(log(heatmapGdal1[,1:4]+1)))), col=circlize::colorRamp2(breaks=c(-1.5,0,1.5), c("blue","white","red")), column_labels=c("Scr #1","CiGdal1 #1","Scr #2","CiGdal1 #2"),column_names_rot=45, column_names_centered=F, column_names_gp=gpar(fontsize=9), cluster_rows=FALSE, cluster_columns=FALSE, show_row_names=FALSE, border=T, show_heatmap_legend=F, 
	# heatmap_width=unit(1.4, "in"), heatmap_height=unit(2, "in"),
	row_split=factor(rep(c("down-regulated", "up-regulated"), c(476,354)),levels=c("down-regulated","up-regulated")),row_title_gp = gpar(font=1,fontsize=9),
	right_annotation=rowAnnotation(myeloid_gene = anno_mark(at = c(201,207,501,543,592,635),labels = c("Jak2","Clec5a","Pml","Plscr1","Dab2","Cebpa"), 
					labels_gp=gpar(font=1,fontsize=9),
					link_width = unit(5, "mm"), #线长度
					padding = unit(5, "mm"), # 标签间隔 
					extend = unit(0, "mm")))
	)

lgd = Legend(col_fun=circlize::colorRamp2(breaks=c(-1.5,0,1.5), c("blue","white","red")),title = "Z-score",title_position="topleft",title_gp = gpar(font=1,fontsize=9),at=c(-1.5,0,1.5),labels_gp = gpar(fontsize=9, font = 1),title_gap=unit(2,"mm"))

tiff(file="figure4a_Genes.tiff",width=2.75, height=2.65, units="in",type="cairo",pointsize=9,res=300)
draw(ht,padding=unit(c(0,0,0.05,0.6),"in"))
draw(lgd, x = unit(0.9, "npc"), y = unit(0.8, "npc"))
dev.off()


